executor: slurm

# Slurm specific
default-resources:
    slurm_account: "dscolab"
    slurm_partition: "dscolab,krummellab,common"
    runtime: 60 # in min
    mem_mb: 20000 # 20gbs
    nodes: 1

jobs: 5 # How many jobs can we execute in parallel
printshellcmds: True
restart-times: 0 # How many times do retry jobs that fail
singularity-args: " -B output/gurobi.lic:/src/compass/compass/gurobi.lic "