## Params
- display: "1__Dataset__name of sc_seq_dataset record"
  ui_component: "magma-record"
  doc: "Choose which sc_seq_dataset to work with."
  input:
    preset:
      modelName: 'sc_seq_dataset'
      targetAtt: 'name'
      otherAttsShow: ['group_id', 'description', 'metadata_annots_fine', 'metadata_annots_broad']
      hasAtts: ['seurat_object']
  output:
    params: [ "dataset_name" ]
- display: "2__Pseudobulking__Minimum cell cutoff"
  ui_component: "int"
  default: 10
  doc: "Establishes the minimum number of cells to use in pseudobulking the dataset. Pseudobulking will be skipped for a given sample and cell type if there are fewer than this many cells."
  output:
    params: [ "min_cells" ]
- display: "2__Pseudobulking__Re-Normalize within metabolic genes"
  ui_component: "dropdown"
  doc: "Establishes whether to pseudobulked counts data should be normalized towards counts of all genes of the dataset versus towards only the metabolic genes that will be used by Compass."
  input:
    preset:
      options: 
        - "No__To_all_genes"
        - "Yes__Only_to_metabolic_genes"
  default: "Yes__Only_to_metabolic_genes"
  output:
    params: [ "pre_process_norm_method" ]
- display: "3__Compass__species"
  ui_component: "dropdown"
  doc: "..."
  input:
    preset:
      options:
        - "human"
        - "mouse"
  default: "human"
  output:
    params: [ "species" ]
- display: "4__Post-processing__Reaction Score Normalization Method"
  ui_component: "dropdown"
  doc: "Establishes if and how to normalize metabolic reaction scores (the negative log transformation of directly output reaction penalties) after compass has been run. The preferred method is currently unknown. Options are:\n\t-\"None\": use scores as-is.\n\t-\"Sum\": normalize reaction scores based on their proportion out of the sum of each meta-subsystem's reaction scores.\n\t-\"Rank\": apply rank-based normalization to compass outputs, per sample/pseudobulk, where the lowest scoring reaction will receive a value of 1, and the highest scoring reaction will receive a value equal to the number of reactions."
  input:
    preset:
      options:
        - "None__as-is"
        - "Sum__divide_by_sum_per_susbsystem"
        - "Rank__rank_reactions_per_pseudobulk"
  default: "Rank__rank_reactions_per_pseudobulk"
  output:
    params: [ "post_process_norm_method" ]
- display: "4__Post-processing__Reaction meta-subsystem target"
  ui_component: "dropdown"
  doc: "This UI establishes the metabolic meta-subsystem to plot. Note: All three meta-subsystems will be run through compass regardless, so you will be able to cycle through each while analyzing!"
  default: "LIPID_META_SUBSYSTEM"
  input:
    preset:
      options: ["CENTRAL_CARBON_META_SUBSYSTEM", "AA_META_SUBSYSTEM", "LIPID_META_SUBSYSTEM"]
  output:
    params: [ "post_process_meta_subsystem" ]

## Input UIs
- display: "Provide Gurobi License"
  name: get_gurobi_license
  ui_component: "multiline-string"
  doc: "... sets the gurobi license for running compass"
  output:
    files: ["gurobi_license_string.txt"]
- display: "Pseudobulking: Sample Metadata Column Name"
  name: ui_select_sample_metadata
  ui_component: "dropdown"
  doc: "Recommendation: Check the target record's '' attributes. Establishes the column name of the cells metadata that holds sample identities of cells. Pseudobulking will rely on this column, which affects everything downstream."
  input:
    files: ["scdata_discrete_opts_no_recs_added.json", "scdata_sample_rec.json"]
  output:
    files: [ "sample_metadata.txt" ]
- display: "Pseudobulking: Cell-Types Metadata Column Name"
  name: ui_select_cell_type_metadata
  ui_component: "dropdown"
  doc: "Recommendation: Check the target record's 'metadata_annots_fine' or 'meatdata_annots_broad' attributes. Establishes the column name of the cells metadata that holds cell type identities of cells. Pseudobulking will rely on this column, which affects everything downstream."
  input:
    files: ["scdata_discrete_opts_no_recs_added.json", "scdata_celltype_rec.json"]
  output:
    files: [ "celltype_metadata.txt" ]
- display: "Reaction Summaries Plot: Cell groups to compare"
  name: ui_diff_targets_cells
  ui_component: "two-group-selection"
  doc: "For plotting metabolic differences, this UI establishes sample/cell groupings to compare. First, you will choose a metadata column of the dataset. Then you will choose two sets of values of that metadata to compare across."
  input:
    files: [ "pseudobulk_discrete_metadata_summary.json" ]
  await_files: [ "compass_output" ]
  output:
    files: [ "diff_group_1__formula.json", "diff_group_2__formula.json" ]

## Output UIs
- display: 'Download Compass Results'
  ui_component: "link"
  input:
    files: [ "compass.tar.gz" ]
- display: 'Comparison Group Summaries'
  ui_component: "collapsible-markdown"
  input:
    files: [ "diff_groups_summary.md" ]
- display: "Display Differential Reaction Summary Plot"
  ui_component: "plot"
  input: 
    files: [ "red_blue.png" ]
- display: 'Download Stats Results - Reactions'
  ui_component: "link"
  input:
    files: [ "group_diff_reaction_stats.tsv" ]
- display: 'Download Stats Results - Subsystems'
  ui_component: "link"
  input:
    files: [ "group_diff_subsystem_stats.tsv" ]
