## Params
- display: "Dataset__name of sc_seq_dataset record"
  ui_component: "magma-record"
  doc: "Choose which sc_seq_dataset to work with."
  input:
    preset:
      modelName: 'sc_seq_dataset'
      targetAtt: 'name'
      otherAttsShow: ['group_id', 'description', 'metadata_annots_fine', 'metadata_annots_broad']
      hasAtts: ['seurat_object']
  output:
    params: [ "dataset_name" ]
- display: "Pseudobulking__Minimum cell cutoff"
  ui_component: "int"
  default: 10
  doc: "Establishes the minimum number of cells to use in pseudobulking the dataset. Pseudobulking will be skipped for a given sample and cell type if there are fewer than this many cells."
  output:
    params: [ "min_cells" ]
- display: "Pseudobulking__Sample Metadata Column Name"
  ui_component: "string"
  doc: "Recommendation: Check the target record's '' attributes. Establishes the column name of the cells metadata that holds sample identities of cells. Pseudobulking will rely on this column, which affects everything downstream."
  output:
    params: [ "sample_id_column" ]
- display: "Pseudobulking__Cell-Types Metadata Column Name"
  ui_component: "string"
  doc: "Recommendation: Check the target record's 'metadata_annots_fine' or 'meatdata_annots_broad' attributes. Establishes the column name of the cells metadata that holds cell type identities of cells. Pseudobulking will rely on this column, which affects everything downstream."
  output:
    params: [ "cell_type_column" ]
- display: "Normalization__method"
  ui_component: "dropdown"
  doc: "Establishes additional normalization to be performed. The best or preferred method is currently unknown, so we offer all options that the compass team reported assessing. Options are:\n\t-None: Utilize read-depth normalization of original data and don't apply anything after running Compass.\n\t-Early__depth_norm_to_metabolic_genes: Re-apply read-depth normalization after trimming to only genes that will be used by Compass.\n\t-Late__by_reaction_sum: Utilize read-depth normalization of original data for running compass, then normalize all reaction scores, per sample, based on their proportion of the sum of all calculated reaction scores.\n\t-Late__by_reaction_rank: Utilize read-depth normalization of original data for running compass, then apply a rank-based normalization to compass outputs, per sample, where the lowest scoring reaction will receive a value of 1, and the highest scoring reaction will receive a value equal to the number of reactions."
  input:
    preset:
      options: 
        - "None__no_additional_normalization"
        - "Early__depth_norm_to_metabolic_genes"
        - "Late__by_reaction_sum"
        - "Late__by_reaction_rank"
  default: "Early__depth_norm_to_metabolic_genes"
  output:
    params: [ "norm_method" ]
- display: "Compass__species"
  ui_component: "dropdown"
  doc: "..."
  input:
    preset:
      options:
        - "human"
        - "mouse"
  default: "human"
  output:
    params: [ "species" ]

## Input UIs
- display: "Reaction Summaries Plot: Cell groups to compare"
  name: ui_diff_targets_cells
  ui_component: "two-group-selection"
  doc: "For plotting metabolic differences, this UI establishes sample/cell groupings to compare. First, you will choose a metadata column of the dataset. Then you will choose two sets of values of that metadata to compare across."
  input:
    files: [ "pseudobulk_discrete_metadata_summary.json" ]
  await_files: [ "compass_outputs/CENTRAL_CARBON_META_SUBSYSTEM/reactions.tsv" ]
  output:
    files: [ "diff_group_1__formula.json", "diff_group_2__formula.json" ]
- display: "Reaction Summaries Plot: Reaction subsystem"
  name: ui_diff_targets_subsystem
  ui_component: "dropdown"
  doc: "For plotting metabolic differences, this UI establishes the set of Compass reactions to focus on."
  input:
    preset:
      options: ["CENTRAL_CARBON_META_SUBSYSTEM", "AA_META_SUBSYSTEM", "LIPID_META_SUBSYSTEM"]
  await_files: [ "compass_outputs/CENTRAL_CARBON_META_SUBSYSTEM/reactions.tsv" ]
  output:
    files: [ "diff_subsystem_target.txt" ]

## Output UIs
- display: 'Download Compass Results'
  ui_component: "link"
  input:
    files: [ "compass.tar.gz" ]
- display: 'Comparison Group Summaries'
  ui_component: "collapsible-markdown"
  input:
    files: [ "diff_groups_summary.md" ]
- display: "Display Differential Reaction Summary Plot"
  ui_component: "plot"
  input: 
    files: [ "red_blue.png" ]
# - display: 'Download Stats Results'
#   ui_component: "link"
#   input:
#     files: [ "stats_output.tsv" ]
